### ISSUE TITLE
KSU 9.1 kernel problems

### ISSUE THREAD

**Issue by vGreatDragon** [Coconutat/android_kernel_huawei_hi3660_emui9.1.0_KernelSU#2]
Huawei Nova 2s device: I tried to use the KSU 9.1 kernel on the stock firmware EMUI 9.1 and HarmonyOS 2.0 The KSU kernel in permissive mode, does not start, Bootloop.. And the kernel in enforcing mode, starts the system but Wi-Fi disappears. This is true for both cores v9 and 10.

**Comment by gemspiderofficial** [comment]
I also have this problem about bootloop in permissive mode but in enforcing everything works well except the restart and offline charging does not work when i have kernelsu

**Comment by Coconutat** [comment]
> Huawei Nova 2s device: I tried to use the KSU 9.1 kernel on the stock firmware EMUI 9.1 and HarmonyOS 2.0 The KSU kernel in permissive mode, does not start, Bootloop.. And the kernel in enforcing mode, starts the system but Wi-Fi disappears. This is true for both cores v9 and 10.
  
***
Maybe Nova 2S is not supported. In the future, if I have time, I will try creating a kernel using the source code of Nova 2S.And the kernel of HarmonyOS is not universal to this.

**Comment by Coconutat** [comment]
> I also have this problem about bootloop in permissive mode but in enforcing everything works well except the restart and offline charging does not work when i have kernelsu

Your device is also Nova 2S ?

**Comment by gemspiderofficial** [comment]
Huawei Honor 9 kirin 960 EMUI 9.1 enforcing

**Comment by vGreatDragon** [comment]
I used your older kernel KSU P10 V0.6.1 9.1.0 and it worked fine on EMUI 9.1 and HarmonyOS 2.0. HarmonyOS just made a new shell, the core is the same as EMUI 9.1. Kernel v0.6.1 worked properly. But then the version was upgraded and it became no longer relevant. I always experiment with your two versions, the general v9 and for P10, I didn’t see any difference at all.                                                                                                                                                                                     I read somewhere that the WIFI module can be built into the core itself, and it works even better.

**Comment by Coconutat** [comment]
> I used your older kernel KSU P10 V0.6.1 9.1.0 and it worked fine on EMUI 9.1 and HarmonyOS 2.0. HarmonyOS just made a new shell, the core is the same as EMUI 9.1. Kernel v0.6.1 worked properly. But then the version was upgraded and it became no longer relevant. I always experiment with your two versions, the general v9 and for P10, I didn’t see any difference at all. I read somewhere that the WIFI module can be built into the core itself, and it works even better.

I'm not sure what happened, updating KSU actually resulted in the inability to use WIFI or power on.But I know one thing is certain. KSU changed the code for SELinux status. Even if you enable kernel SELINUX permissive, it will transition to enforcing mode.
