### ISSUE TITLE
Wi-Fi does not work

### ISSUE THREAD

**Issue by Dimlos-jp** [Coconutat/android_kernel_huawei_hi3660_emui9.1.0_KernelSU#3]
I installed it on Mate9 with EMUI 9.1, but Wi-Fi does not work.

**Comment by Coconutat** [comment]
> I installed it on Mate9 with EMUI 9.1, but Wi-Fi does not work.

Try another kernel.V9 version or P10 Version.

**Comment by Dimlos-jp** [comment]
Since Huawei support has expired, changes from 9.1.0.275 are not possible.
Could you please build a kernel that will work in this environment?

**Comment by Coconutat** [comment]
> Since Huawei support has expired, changes from 9.1.0.275 are not possible. Could you please build a kernel that will work in this environment?

I have released two different versions of the kernel. One is Honor V9, and the other is the version of Huawei P10. The difference between them is that the WiFi driver is different. What I mean is that you can download compressed packages containing P10 or V9 tags for testing. Some Huawei models may have mixed WiFi modules.
