### ISSUE TITLE
Restart and Offline Charging

### ISSUE THREAD

**Issue by gemspiderofficial** [Coconutat/android_kernel_huawei_hi3660_emui9.1.0_KernelSU#4]
Both not working when i try to restart it will just turn off and will not turn on again unless i power it on same for offline charging when powered off it will not charge or show any charging screen

**Comment by Coconutat** [comment]
> Both not working when i try to restart it will just turn off and will not turn on again unless i power it on same for offline charging when powered off it will not charge or show any charging screen

If I had time,I will fix it.
